### ISSUE TITLE
Cant access Web server

### ISSUE THREAD

**Issue by RussianGuy123** [swisspol/ComicFlow#101]
Hello, since last week. 
It is really unfortunate, I was so happy with ComicFlow. 
I think about reinstalling, but before I do that I have a 2 questions:
1. Will my comic book library dissapear after installation?
2. Will it still recognize that I puchased ComicFlow after reinstallation?
Thank you very much in advance (

**Comment by swisspol** [comment]
1. If you delete the app from your iPad and re-install it, then yes, all the comics will be gone
2. Use the "Restore purchase" option in the settings panel

Note that until you get Web Server to work again (try on a different WiFi network, try WebDAV vs regular server, try Mac vs PC, etc...), you can upload through iTunes (see help in description of app at https://itunes.apple.com/us/app/comicflow/id409290355?mt=8).
