### ISSUE TITLE
Unable to upload any files on new ipad

### ISSUE THREAD

**Issue by i3kama** [swisspol/ComicFlow#102]
I used to have an old ipad and comic flow worked like a charm. Then I bought a new one (ipad air 2). I downlaoded the app and restored the previous purchase. Then I went off and tried to upload files but it didn't work. I tried both webserver and webDAV both from a mac and a windows machine with three different browsers.

The log fil in ComicFlow says things like : "Warning No data received from socket 13"

The webinterface says: "Forbidden: Failed uploading "XYZ.jpg" to "/"
WebDav client says:

> PROPFIND / HTTP/1.1
> Depth: 1
> Content-Type: text/xml; charset=utf-8
> Content-Length: 99
> Host: 192.168.1.116
> Connection: Keep-Alive
> User-Agent: Cyberduck/5.0.3.20504 (Windows 7/6.1) (x86)
> Accept-Encoding: gzip,deflate
> Authorization: Basic YW5vbnltb3VzOmN5YmVyZHVja0BleGFtcGxlLm5ldA==
> HTTP/1.1 207 Multi-Status
> Cache-Control: no-cache
> Content-Length: 548
> Content-Type: application/xml; charset="utf-8"
> Connection: Close
> Server: ComicFlow Web Server 1.4.3 (143000)
> Date: Tue, 05 Jul 2016 14:29:35 GMT
> PUT /XYZ.jpg HTTP/1.1
> Expect: 100-continue
> Content-Length: 831621
> Content-Type: image/jpeg
> Host: 192.168.1.116
> Connection: Keep-Alive
> User-Agent: Cyberduck/5.0.3.20504 (Windows 7/6.1) (x86)
> Accept-Encoding: gzip,deflate
> Authorization: Basic YW5vbnltb3VzOmN5YmVyZHVja0BleGFtcGxlLm5ldA==
> HTTP/1.1 403 Forbidden
> Content-Length: 228
> Content-Type: text/html; charset=utf-8
> Connection: Close
> Server: ComicFlow Web Server 1.4.3 (143000)
> Date: Tue, 05 Jul 2016 14:29:35 GMT
> PUT /XYZ.jpg HTTP/1.1
> Expect: 100-continue
> Content-Length: 831621
> Content-Type: image/jpeg
> Host: 192.168.1.116
> Connection: Keep-Alive
> User-Agent: Cyberduck/5.0.3.20504 (Windows 7/6.1) (x86)
> Accept-Encoding: gzip,deflate
> Authorization: Basic YW5vbnltb3VzOmN5YmVyZHVja0BleGFtcGxlLm5ldA==
> HTTP/1.1 403 Forbidden
> Content-Length: 228
> Content-Type: text/html; charset=utf-8
> Connection: Close
> Server: ComicFlow Web Server 1.4.3 (143000)
> Date: Tue, 05 Jul 2016 14:29:38 GMT
> 

Am I doing something wrong? Can't find that anyone else is having any problems.

/Martin

**Comment by swisspol** [comment]
The one thing left to try would be a different WiFi if you haven't already?

Looks like you're getting 403 errors from the server. You could try re-installing the app.

**Comment by i3kama** [comment]
Hi
I have now done the following:
Uninstalled the app
Reinstalled it
Tried again and failed
Tried to "Restore Precious Purchase" which failed(!) (due to reinstall?)
Tried on different wifi network but also failed. 

Is there some setting on the ipad that could be wrong? Is apple tightening up something? I am running ios 9.3.2

Are there other options how to upload files?

**Comment by swisspol** [comment]
If you have problems with "Restore Precious Purchase", you might have to restart your iPad.

I can't think of anything, sorry. Nobody else has reported such a problem and I've never seen it myself (I also use ComicFlow with WebDAV on an iPad Air 2).

You can upload comics through iTunes: see description at https://itunes.apple.com/us/app/comicflow/id409290355?mt=8.
