### ISSUE TITLE
Feature Request: PIL.ImageColor.getrgb("hsl(hue,sat%,lig%.)") allow values to be decimal/float numbers

### ISSUE THREAD

**Issue by MortenZdk** [swisspol/ComicFlow#105]
The values in doing PIL.ImageColor.getrgb("hsl(hue, sat%, lig%)") must currently be integer, but this limits the resulting RGB color resolution, since a difference of 1 as minimum step for arguments does sometimes results in a difference for RGB value of up to about 5, thus not allowing the function to control the value fine grained.

**Comment by swisspol** [comment]
Looks like you are in the wrong project :)

**Comment by MortenZdk** [comment]
Sorry, my fault; thanks for closing the wrong issue. Best regards Morten.
