### ISSUE TITLE
Feature Request: PIL.ImageColor.getrgb add support for HSB/HSV format

### ISSUE THREAD

**Issue by MortenZdk** [swisspol/ComicFlow#106]
The current PIL.ImageColor.getrgb does not support [HSB/HSV](https://en.wikipedia.org/wiki/HSL_and_HSV) format, only the related HSL, but for easier conversion of some coordinates it would be nice to have support for HSB/HSV also.

**Comment by swisspol** [comment]
Looks like you are in the wrong project :)

**Comment by MortenZdk** [comment]
Sorry, my fault; thanks for closing the wrong issue. Best regards Morten.
