### ISSUE TITLE
Previous Versions

### ISSUE THREAD

**Issue by Comicphantom** [swisspol/ComicFlow#107]
I recently acquired a Gen 1 IPad that I would like to make a dedicated comic book reader.  I've heard wonderful things about your software and that is compatible with IOS 5.1.1

Sadly the current version on ITunes needs IOS 6.  Can some one point me to where I can find a previous version of this software that would be compatible?

**Comment by swisspol** [comment]
Are you sure that when you use the App Store app on this iPad it offers you to download the latest version of ComicFlow instead of the latest one compatible with the device?

**Comment by Comicphantom** [comment]
Yes.  it says i cannot  download the App because it requires IOS 6



Sent from my Sprint Samsung Galaxy® Note 4.


-------- Original message --------

**Comment by swisspol** [comment]
I cannot give you the app myself, but there's some help here: http://apple.stackexchange.com/questions/195074/how-do-i-install-an-older-version-of-an-app-on-an-iphone
