### ISSUE TITLE
WebDav 403 Forbidden on upload

### ISSUE THREAD

**Issue by wrrzag88** [swisspol/ComicFlow#110]
Hi,
I've been using ComicFlow for a while and let me congratulate you for the amazing work!!!
But, I have a problem uplaoding files... I have reached the 50 uploaded files using webserver and I'm trying to upload using webdab, as I specify in the title, every time I upload a file, no matter why, I'have used Cyberduck, Finder and other clients, and had the same result, Error 403 Forbidden.

Any solution?? Thank you

**Comment by swisspol** [comment]
WebDAV and WebServer both have the 50 uploads limitation. You need to purchases the in-app option to unlock the unlimited WebDAV / WebServer.
