### ISSUE TITLE
Incomplete version paid

### ISSUE THREAD

**Issue by sarmario** [swisspol/ComicFlow#112]
After you have paid for the full version, the app appears as incomplete. Invientao again to pay if I want to use "purchase unlimited web server". Also it does not allow me to upload more files because of this.

**Comment by swisspol** [comment]
Hi,

Sorry about that: try force-quitting the app, relaunching it, then going into Settings and tapping "Restore purchases".

**Comment by sarmario** [comment]
I have already done it and nothing

**Comment by swisspol** [comment]
You can try re-installing the app. Make sure you have the very latest version AND that you are using the same Apple ID you used at the time to purchase.
