### ISSUE TITLE
Unresponsive Server

### ISSUE THREAD

**Issue by namorski** [swisspol/ComicFlow#118]
I'm unable to connect to the server via IP address, or WebDAV. I'm currently running iOS 10.3.3 on my iPad.

**Comment by namorski** [comment]
Any suggestions for a solve?? Not like it was a massive expenditure, but I ponied up for the unlimited storage. Aside from the server issue, it's a wonderful app, and I'd like to keep using it.

**Comment by swisspol** [comment]
Hi,

I would say restart your iPad and try on a different WiFi network.

**Comment by namorski** [comment]
Thanks for getting back to me. I tried restarting, and accessing the platform on a different WiFi network, and was unsuccessful. This is the messaging I receive:

![screen shot 2017-12-09 at 12 23 48 am](https://user-images.githubusercontent.com/34292043/33792796-50924450-dc77-11e7-8dec-7fe1de03ba5c.png)

**Comment by namorski** [comment]
Hi, would you have a solution for this issue? I've tried accessing on a different machine, and still can't connect. This is what I get from the WebDAV platform:
![screen shot 2017-12-16 at 10 32 34 pm](https://user-images.githubusercontent.com/34292043/34076359-122a4398-e2b2-11e7-8717-d616dc2eeb25.png)

**Comment by namorski** [comment]
Nevermind, I'll just add through iTunes.

**Comment by writewood** [comment]
Has this question been answered elsewhere? The server worked perfectly until the day I paid for the unlimited plan, when it suddenly stalled altogether. Page won't even load. Please advise or pass along how I can be refunded.
