### ISSUE TITLE
Web server importing does not work

### ISSUE THREAD

**Issue by NSHkD** [swisspol/ComicFlow#122]
Affects both the website and webDAV methods on iOS 11.3.1 (iPad Air 2).

Attempting to upload via the web site will give a generic error message: "error: Failed uploading "xxx" to "yyy"". Some attempts will give another error message in the app log: "Error while writing to socket 68: Broken pipe (32)". The socket number varies with each message. This error does not happen with the majority of attempted uploads however.

Attempting to upload via webDAV (using Windows Explorer) will immediately prompt that there is already a file by that name and ask if you want to replace it. Attempting to replace will give the error "Can't read from the source file or disk". In the end, a 0 byte file of the same name is left over. No error messages in the app log show up with this method.

File moving & deletion, as well as creating folders, all still work with both methods.

**Comment by MichaelGallo** [comment]
I have exactly the same issue, iPad Pro 12" 2017, iOS 11.4.

**Comment by rodleeo** [comment]
I'm not beeing abble to reorganize my library with the webDAV method anymore. It won't even connect to the server, sadly. I changed my internet provider recently and hadn't done any config yet. Maybe that's the problem. Anyone here has suffered with the same issue?
