### ISSUE TITLE
Upload forbidden with purchaced version

### ISSUE THREAD

**Issue by rolandbreedveld** [swisspol/ComicFlow#124]

**Comment by swisspol** [comment]
Is the website working, can you browse around the folders?

Can you provide a screenshot of the error when you try to upload?

**Comment by rolandbreedveld** [comment]
problem solved, reinstall it again (twice) solves the problem

**Comment by rolandbreedveld** [comment]
perhaps some cache issues, from the old one

**Comment by swisspol** [comment]
Glad to hear, thanks!

**Comment by rolandbreedveld** [comment]
still, comics in epub format are forbidden, but converting them to cbr solves it to.
