### ISSUE TITLE
Comic Flow on a new device 

### ISSUE THREAD

**Issue by OlaviMed** [swisspol/ComicFlow#125]
My old iPad died and when I downloaded this app it does not do anything when I choose the option Restore Previous Purchase, so I can’t use the full version I had purchased

**Comment by swisspol** [comment]
Hi,

Did you try deleting the app, restarting your iPad, then redownloading it and finally tapping “Restore Previous Purchase”?

**Comment by OlaviMed** [comment]
It does not work. Thank you anyway

**Comment by swisspol** [comment]
The only thing I can think of is that the Apple ID for the App Store on your iPad doesn't match the one used to purchase ComicFlow at the time.
