### ISSUE TITLE
Reorganizing library

### ISSUE THREAD

**Issue by rodleeo** [swisspol/ComicFlow#126]
Hello, everyone! 

I only recently discovered the ComicFlow app and I must say it's, BY FAR, the best experience I have had on my old iPad 2 when it comes down to reading comic books. However, considering there's dozens of books in my library, it has been hard to organize and put them in a proper order or even catalogue them in separate "series". With that in mind, I'd like to know if it's possible, through the WebServer link the app provides, to reorganize my library (by that I mean creating folders and moving the books to it's especific series's) without having to delete all my content and upload them again over WiFi, especially considering I can only do it 50 items for free. I would really appreciate if someone could help me figuring that out. 

Thank you!

**Comment by swisspol** [comment]
Hi,

Glad you like ComicFlow, thanks! To organize comics after having uploaded them, you'll want to use the WebDAV server. It cannot be done from the UI inside the app nor from the WebServer. With WebDAV server and an app like https://cyberduck.io/ you can move the comic files between folders and also create new folders. Note that you cannot have subfolders, this is not supported. It's pretty limited overall but beats reuploading everything in folders.

**Comment by rodleeo** [comment]
Oh, thank you so much! I'm really an illiterate when about that stuff, but I'm going to try my best. If any struggle comes through, I'll report back and maybe abuse of your kindness just a little bit more :)
Thank you very very much, I really appreciate you taking time from your day to help me out. Have a nice week! 

P.S.: I'm from Brasil and my english didn't improve much along the years, so please apologize me if I made any mistakes.
