### ISSUE TITLE
webDAV connection closed

### ISSUE THREAD

**Issue by rodleeo** [swisspol/ComicFlow#128]
Hello! Firts, I want to say thank you for ComicFlow app. It has such a great user experience! Always extremely fluid and light (even on older devices, like my almost jurassic iPad 2).

I'm here to report that the webDAV connection method has been off for a few days. Whenever I try to use my installed software (BitKnex) to acess my storaged content, I receive a message that says "Connection Closed". Everything has been working nicely since I discovered this function last month. As I'm a complete "organization freak", my unorganized library is driving me utterly nuts haha

I also tried to establish connection using 2 different softwares, but wasn't sucessful in neither of them.

For further notice, the web server seems to be on normally. I had just uploaded a bok to the desired folder and everything went well, without any error messages.

I really hope I can get some help with this. It would mean a big deal for me.

Wish you all a really nice week.

Thank you!

**Comment by swisspol** [comment]
Hi! Sorry for the delay. All I can say is that nothing has changed in ComicFlow for the past 2 years. So it has to come from your WiFi network. I’d suggest trying on a different one.
