### ISSUE TITLE
How come you have paid features (like the web server) ?

### ISSUE THREAD

**Issue by Holyprogrammer** [swisspol/ComicFlow#130]
Okay, so, I have no idea how this works, but the way I see it, couldn't I just download your source code and edit it to make all in app purchases free? If it was possible, I would put a "Logic-hole" tag on this...

**Comment by swisspol** [comment]
Sure you could do that. That is if you are willing to spend anywhere from up to few hours figuring everything out. Or you could pay $3 to enable this feature. It all depends on how technical you are and how you value your time 😃

**Comment by KhushrajRathod** [comment]
Hey @swisspol, I just stumbled across this again (It was my first GitHub issue)... This was a while ago, and now that I read it my comment seems very _rude_, just wanted to apologise :)

**Comment by aaryanporwal** [comment]
LMAO
