### ISSUE TITLE
Can’t access ComicFlow to add/edit comics on IPad 

### ISSUE THREAD

**Issue by ChrisQuarrie2** [swisspol/ComicFlow#137]
My “iPad-air-2-local” web address no longer loads my iPad library (yes, ComicFlow is open on iPad) so I can’t add / edit comics

**Comment by spikebyt** [comment]
I came here today searching for that same problem. I'm unable to add files from my NAS to my iPAd Air. I even purchased webserver support, but no success so far. Can anyone tell me how to fix this

**Comment by swisspol** [comment]
ComicFlow settings pop up window will show you the address to use to connect to it.
