### ISSUE TITLE
[Request] [Question]

### ISSUE THREAD

**Issue by BMoreno84** [swisspol/ComicFlow#138]
My request:

Im sure you’re tired of hearing this, but can this app get an iPhone version? There are other apps that offer it, but dont have the same transfer features your does. 

Panels, is an example and it works great. However they lack WebDAV and other things.

My Question:

Is this app going to continue receiving updates, or are you done with it?

**Comment by swisspol** [comment]
There are no iPhone version planned.

ComicFlow is in maintenance mode and only receives critical bug fixes.
