### ISSUE TITLE
Restore Previous Purchase function not working

### ISSUE THREAD

**Issue by pogomonkeytutu** [swisspol/ComicFlow#139]
I've switched to a new iPad and, having downloaded Comic Flow to my new device, the Restore Previous Purchase option isn't doing anything. I click it and nothing happens. I'm signed into the same Apple ID for the App Store so it's not that.

**Comment by swisspol** [comment]
I haven't heard of anyone else having this issue, so that's strange. What's the OS version? Can you try restarting your iPad and trying one more time?
