### ISSUE TITLE
Can´t upload

### ISSUE THREAD

**Issue by kasovitz** [swisspol/ComicFlow#140]
Hello I purchase the unlimited webserver, this month and after that I can't connect and upload the files, how can I solve this?

Thanks
Ricardo

**Comment by swisspol** [comment]
What exact errors do you get? What OS / app are you using to upload?

**Comment by kasovitz** [comment]
Salut Pierre, merci pour ton e-mail, après une semaine durant laquelle je n'ai pas pu fair upload the BD, il a commencer a travailler sans que je fasse quoi que ce soit :) merci beaucoup, j'aime beaucoup l'application et à ce stade cela aide beaucoup à passer le temps.

merci beaucoup
Keep Safe

Instagram: ricardomiguelferreira​
Portfolio: https://spark.adobe.com/page/HmRPG0fXbIgme/
Digital alchemist - Graphic Fashion - Font landscape architect - Blank space designer - Collector of memories within photos - Internet hunter.


________________________________
De: Pierre-Olivier Latour <notifications@github.com>
Enviado: 25 de março de 2020 21:08
Para: swisspol/ComicFlow <ComicFlow@noreply.github.com>
Cc: kasovitz <ferreiranet@msn.com>; Author <author@noreply.github.com>
Assunto: Re: [swisspol/ComicFlow] Can´t upload (#140)


What exact errors do you get? What OS / app are you using to upload?

**Comment by swisspol** [comment]
Super!
