### ISSUE TITLE
Can't move to a folder with spaces in the name

### ISSUE THREAD

**Issue by Brunoesp** [swisspol/ComicFlow#141]
I'm trying to move a file to a folder with spaces (e.g. "Some Comics") both in website and webdav mode. In website I couldn't figure out the syntax and in webdav (move command) it fails with "409 - conflict". Tried using quotation marks and escaping the spaces, nothing worked.

**Comment by swisspol** [comment]
Can you provide the log of the server? You can show it from the settings window and then copy paste it.

**Comment by Brunoesp** [comment]
Everything the log says after starting webDAV is `Unknown DAV property requested "checked-in" and 
"checked-out"`. Tried a bunch of commands and all give the same log. 
`move "comic" "some folder"` fails with 409 conflict. The same for copy command.
`move "comic" "somefolder"` succeeds, the same for `move "comic" somefolder`.

Could you provide me the precise syntax to move to a folder with spaces in the website mode so I can try?

**Comment by Brunoesp** [comment]
For now, a workaround is to move files to a folder with no spaces in the name, then rename the folder after.

**Comment by swisspol** [comment]
I think it may be your WebDAV client that's doing something not supported by https://github.com/swisspol/GCDWebServer

**Comment by Brunoesp** [comment]
I was using 'cadaver' client. Tried with the 'nautilus' file manager and successfully moved the file.
