### ISSUE TITLE
Add support for right-to-left reading

### ISSUE THREAD

**Issue by liwic** [swisspol/ComicFlow#66]
hi this is a great program, however, I would like to request two feastures
1. an alternative page flipping orientation,  instead of Left to Right, can it also add right to left ?   most asian books and magazines are read from Right to Left, thank you.   
2. also if possible, view two page at once. (this allows some scenes spanning two pages be viewed at once.  Of course to like up properly, probably need a shift by 1 page option as well.

**Comment by ioc32** [comment]
@swisspol @liwic +1 to the alternative page flipping orientation :)

**Comment by KnightBaron** [comment]
+1 Right-to-left is a deal breaker for me.

**Comment by MukiEX** [comment]
Closed "LOL DGAF"
