### ISSUE TITLE
Newbie help needed

### ISSUE THREAD

**Issue by ThirstyMan** [swisspol/ComicFlow#78]
I am not very computer literate. I have bought the web server app for my iPad. I have several cbr files on my PC. I would like, in really simple terms, to know how to transfer these to my comic flow library. I started the app and tried to go to 192.168.11.4 on my PC. Using IE, it reports 'this page cannot be displayed.' My iPad and PC are on the same home network.

**Comment by swisspol** [comment]
Hi,

Here's the help from the app description at https://itunes.apple.com/us/app/comicflow/id409290355?mt=8:

```
Importing Comics - iTunes with USB cable:
- Connect your iPad to your computer and launch iTunes
- In the Applications section, select ComicFlow in the list at the bottom
- Drag and drop comic files into the Documents area
- If ComicFlow is already running, display the settings window (upper-right button) and tap on "Update Library"

Importing Comics - Web Server over WiFi (In-App purchase required for unlimited use):
- Make sure your iPad and computer are on the same WiFi network
- Launch ComicFlow
- Display the settings window (upper-right button) and set the Web Server setting to "Website" mode
- Open the provided URL in a web browser on your computer
- To upload comics as part of series, first create a folder then upload the comic files into it
Instead of a web browser, if you prefer to use a WebDAV client (e.g. Transmit or ForkLift for Mac or CyberDuck for Mac / Windows), set the Web Server setting to "WebDAV" mode and connect the client to the provided URL.

Deleting or changing a comic or series status:
- Tap and hold on a comic thumbnail or a series thumbnail
- Choose the appropriate option in the pop-up menu that appears
```

Make sure your iPad and PC can communicate on port 80 on your WiFi network - your router may prevent that.

**Comment by ThirstyMan** [comment]
I think you missed the bit that says I am not computer literate. Yes I followed all above instructions. No clue what is meant by port 80 or how to check whether it is open or not

**Comment by swisspol** [comment]
This is unfortunately not something I can help you with remotely. The best is probably for you to import comics using iTunes and a USB cable (see help I provided previously).
