### ISSUE TITLE
unlimited server not working

### ISSUE THREAD

**Issue by TeamCliegg** [swisspol/ComicFlow#79]
I paid for the in app unlimited server support, but cannot get anything to pull up on the sites and directions Comic Flow gives me. The ap itself has no information on the server other than to turn it on or off, and neither of the websites it directs me to loads. Help?

**Comment by swisspol** [comment]
Hi,

This is most likely a WiFi problem and not a ComicFlow problem. Please see #71 for some troubleshooting steps.
