### ISSUE TITLE
paid app but after reinitialisation I am again in limited mode

### ISSUE THREAD

**Issue by jps01** [swisspol/ComicFlow#85]
I paid comicflow there are already long.
I wanted to reset the app ( to clean it) , and since I have the following message:
upload rejected: web server is in limited fashion .
Thank you for Help 

Jps

**Comment by swisspol** [comment]
Hi,

Thanks for purchasing ComicFlow. You just need to do "Restore Purchases" in the settings pane :)

**Comment by jps01** [comment]
This is the second time I reinit magicflow and now I have this problem well .I use "restore previous purchase ," but nothing happens .
like this I have never bought the app .
is there a solution ?
can you see your side if there is evidence of my payment .
I use the app since February or March 2014 .
thank you

**Comment by swisspol** [comment]
Just try restarting your iPad. It should definitely work as it worked for everyone else.

This is all managed by the App Store, I unfortunately cannot access or even see your purchases, nor enable the feature remotely, sorry.
