### ISSUE TITLE
Library looses read/ unread flags, contents in nested directories don't show

### ISSUE THREAD

**Issue by buggerman** [swisspol/ComicFlow#86]
When I by mistake, put a directory which has another directory inside it, it doesn't show its contents.

Also, if now after this I add a new comic book using iTunes or WebDAV, it marks all my comic books as new.

Please fix. Or am I doing something wrong?

Thanks!

**Comment by swisspol** [comment]
Nested directories are not supported in comicflow: they should just be ignored. You should delete the ones you have added.

**Comment by buggerman** [comment]
Oh okay. Could they be causing the app to lose the read/ unread flag for each book?

**Comment by swisspol** [comment]
I can't say: I've never seen or heard or such a behavior. You can try recreating the library from the settings pane or deleting the app and reinstalling it.

**Comment by buggerman** [comment]
Ok.. Thanks for responding so promptly.. Closing this.. :-)
