### ISSUE TITLE
Feature Request: Better navigation in the library

### ISSUE THREAD

**Issue by jotteerr** [swisspol/ComicFlow#91]
Hi,

when having more than a handful comics in the library, the view "By Name" is rather disorienting and thereby pretty useless. Showing the file name under the thumbviews would be a first help, but if one could switch to a list view (as in the Mac OS X Finder) would be great.

Best
Joachim

**Comment by wafcio** [comment]
Saying that it is useless is not so good, the author added it for some reason. It will be better ask him, how it can be used.
