### ISSUE TITLE
Tapping to enlarge ComicFlow screen 

### ISSUE THREAD

**Issue by Azran123** [swisspol/ComicFlow#93]
Hi,

Another issue is about enlarging the comic screen. In previous version, I could double tap the screen to make it as big as my Ipad Air 2 screen. It was way quicker for me to make the text big enough without streching the view with my fingers. Now whan I double tap the screen becomes way biger then Ipad screen making it very hard to read. Is it possible to do in latest version? If not are you planning to return to this double tap method?

Thanks,

Regards,

Azran

**Comment by swisspol** [comment]
This behavior has not changed since ComicFlow 1.0. You are probably reading a different comic with different image sizes, so they resize differently when double tapping. I can't think of any other reason.
