### ISSUE TITLE
Feature Request: Ability to Create Folders to Organize Comics

### ISSUE THREAD

**Issue by goldenegg** [swisspol/ComicFlow#94]
It would be great to have a way to easily organize the comics and other documents added to ComicFlow.  The 'series' screen is never populated for me, which I'm guessing has to do with a lack of information in the files to perform the proper sorting.  What I'd like to do is create my own folders that I can move documents in to.

**Comment by swisspol** [comment]
Series in ComicFlow must be created manually by putting comic files into folders. Folders within folders are not supported.

You can create folders using the WebDAV or Web Uploader interfaces - see official app description at https://itunes.apple.com/us/app/comicflow/id409290355?mt=8.
