### ISSUE TITLE
Feature Request: Added support for subfolders

### ISSUE THREAD

**Issue by yami7825** [swisspol/ComicFlow#96]
This would make it a lot easier to organize and manage different story arcs within the same series.

**Comment by yami7825** [comment]
@swisspol I just wanted to add, even though I already left a review on the app store; This is a great app, I've already purchased the full web server. Thanks! Keep up the good work :)

**Comment by swisspol** [comment]
Thanks!

**Comment by fauxserve** [comment]
Agreed with yami7825. I've also purchased the full web server and agree that I would love support for recursive subfolders. Thank you!

**Comment by mrfusiontm** [comment]
I just purchased the full server and I agree, sub folder support is essential. 
It appears to let me make subfolders and upload to them, but there doesn't seem to be any way to access the files.  Is there any chance this could get pushed up higher on the todo list?

**Comment by matinciel** [comment]
Clearly yes, it would be SO nice to even add an inapp way to create a folder / sub folder and manage file ! (otherwise great app anyway)
